import base64
from email.message import EmailMessage
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
import os
import logging

logger = logging.getLogger(__name__)

def send_verification_email(to_email: str, display_name: str, action_link: str):
    """
    Sends a gamified HTML verification email using the Gmail API via OAuth 2.0.
    Expects token.json to be present in this directory (generated by gmail_auth.py).
    """
    token_path = os.path.join(os.path.dirname(__file__), 'token.json')
    if not os.path.exists(token_path):
        logger.warning("No token.json found for Gmail API. Mocking email delivery.")
        logger.info(f"MOCK EMAIL: To: {to_email} | Action Link: {action_link}")
        return
        
    creds = Credentials.from_authorized_user_file(token_path, ['https://www.googleapis.com/auth/gmail.send'])
    service = build('gmail', 'v1', credentials=creds)
    
    message = EmailMessage()
    
    content = f"""
    <html>
      <body style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f4f4f5; padding: 40px; text-align: center;">
        <div style="background-color: white; padding: 40px; border-radius: 12px; max-width: 500px; margin: 0 auto; border: 4px solid #141b2b; box-shadow: 6px 6px 0px 0px #141b2b;">
            <h1 style="text-transform: uppercase; font-size: 28px; font-weight: 900; font-style: italic; color: #141b2b;">Welcome to the Guild, {display_name}!</h1>
            <p style="font-size: 16px; margin-bottom: 30px; color: #4b5563;">Your next quest awaits. Click the button below to verify your email and begin your journey.</p>
            <a href="{action_link}" style="display: inline-block; background-color: #4F46E5; color: white; padding: 16px 32px; font-size: 18px; font-weight: 900; font-style: italic; text-transform: uppercase; text-decoration: none; border-radius: 8px; border: 2px solid #141b2b; box-shadow: 4px 4px 0px 0px #141b2b;">Verify Email</a>
        </div>
      </body>
    </html>
    """
    
    message.set_content("Please enable HTML to view this email.")
    message.add_alternative(content, subtype='html')
    
    message['To'] = to_email
    # Using 'me' defaults to the authenticated user (haia.organize@gmail.com)
    message['From'] = 'haia.organize@gmail.com'
    message['Subject'] = 'Join the Guild - Verify Your Haia Account'
    
    encoded_message = base64.urlsafe_b64encode(message.as_bytes()).decode()
    create_message = {'raw': encoded_message}
    
    try:
        service.users().messages().send(userId="me", body=create_message).execute()
        logger.info(f"Successfully sent verification email to {to_email}")
    except Exception as e:
        logger.error(f"Failed to send email via Gmail API: {e}")
        raise
